### ISSUE TITLE
[feat] 프로필 조회 API 구현

### ISSUE THREAD

**Issue by iboyeon0816** [iiqcov/planpal-backend#51]
## Description
프로필 탭의 사용자 정보 및 친구 정보를 조회할 수 있는 API를 구현한다.

## Todo
- [x] 사용자 정보 조회 API 구현
- [x] 친구 목록 조회 API icon 추가
- [x] 친구 요청 목록 조회 API icon 추가
